const Icon = ({ name }: { name: "screen" | "cell" | "shield" | "arrow" | "pin" | "phone" | "mail" }) => {
  const paths = {
    screen: <><rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8M12 17v4"/></>,
    cell: <><circle cx="12" cy="12" r="4"/><circle cx="12" cy="12" r="9"/><path d="M12 3v5M21 12h-5M12 21v-5M3 12h5"/></>,
    shield: <><path d="M12 3 4.5 6v5.5c0 4.6 3.2 7.7 7.5 9.5 4.3-1.8 7.5-4.9 7.5-9.5V6L12 3Z"/><path d="M9 12h6M12 9v6"/></>,
    arrow: <><path d="M5 12h14M14 7l5 5-5 5"/></>,
    pin: <><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>,
    phone: <><path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1 1 .4 2 .7 2.9a2 2 0 0 1-.5 2.1L8 10a16 16 0 0 0 6 6l1.3-1.3a2 2 0 0 1 2.1-.5c1 .3 1.9.6 2.9.7a2 2 0 0 1 1.7 2Z"/></>,
    mail: <><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></>,
  };
  return <svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
};

const treatments = [
  { no:"01",icon:"screen" as const,tone:"mint",eyebrow:"ONLINE CARE",title:"オンライン診療",subtitle:"メディカルダイエットオンライン外来",text:"ご自宅から医師の診察を受けられる、通院不要のオンライン外来です。お身体の状態や目標を確認し、一人ひとりに合った治療をご提案します。",points:["スマートフォンで診察","全国から受診可能","お薬はご自宅へ配送"],href:"https://ge-ginza.clinic/online-diet",cta:"オンライン外来を見る" },
  { no:"02",icon:"cell" as const,tone:"blue",eyebrow:"REGENERATIVE MEDICINE",title:"再生医療",subtitle:"細胞の可能性を、これからの健康へ",text:"患者さまの状態とご希望を丁寧に確認し、再生医療等提供計画に基づく治療を含め、適切な選択肢をご案内します。",points:["自己脂肪由来幹細胞治療","1回あたり1億細胞","完全予約制・少人数対応"],href:"#stem-cell",cta:"幹細胞治療の詳細を見る" },
  { no:"03",icon:"shield" as const,tone:"coral",eyebrow:"CANCER CARE",title:"がん治療",subtitle:"標準治療を尊重した、個別化医療",text:"現在の治療内容や検査結果を確認しながら、主治医との連携を大切に、患者さまに適した治療の可能性を検討します。",points:["がん核酸医療","NK細胞療法","医師による個別相談"],href:"#contact",cta:"がん治療について相談" }
];

export default function Home() { return <main>
  <header className="header"><a className="brand" href="#top" aria-label="ホームへ"><span className="brandMark clinicLogo"><img src="/clinic-logo.png" alt="" width="1460" height="2048"></span><span className="clinicWordmark"><img src="/clinic-brand.png" alt="GRAND ETERNITY グランエタニティ銀座 クリニック" width="1460" height="2048"></span></a><nav aria-label="メインナビゲーション"><a href="#treatments">診療案内</a><a href="#philosophy">当院について</a><a href="#access">アクセス</a></nav><a className="headerCta" href="https://ge-ginza.clinic/reservation/">オンライン診療予約 <Icon name="arrow"/></a></header>
  <section className="hero" id="top"><div className="heroGlow glowOne"/><div className="heroGlow glowTwo"/><div className="heroContent"><p className="kicker"><span/> MEDICAL CARE FOR YOUR FUTURE</p><h1>より健やかに、<br/><em>より自分らしく。</em></h1><p className="heroLead">オンライン診療から再生医療、がん治療まで。<br/>科学的な視点と丁寧な対話で、あなたの未来に寄り添います。</p><div className="heroActions"><a className="primaryBtn" href="#treatments">診療内容を見る <Icon name="arrow"/></a><a className="textLink" href="#contact">まずは相談する <Icon name="arrow"/></a></div></div><div className="heroVisual" aria-hidden="true"><div className="orbit orbitA"/><div className="orbit orbitB"/><div className="core clinicLogo"><img src="/clinic-logo.png" alt="" width="1460" height="2048"></div><div className="floatCard fc1"><span className="dot mint"/><div><small>ONLINE</small><b>いつでも身近に</b></div></div><div className="floatCard fc2"><span className="dot blue"/><div><small>SCIENCE</small><b>先進医療の選択肢</b></div></div><div className="floatCard fc3"><span className="dot coral"/><div><small>PERSONAL</small><b>一人ひとりに寄り添う</b></div></div></div><a className="scroll" href="#treatments"><span>SCROLL</span><i/></a></section>
  <section className="intro" id="treatments"><p className="sectionEyebrow">THREE PILLARS OF CARE</p><h2>3つの診療の柱</h2><p>身近な健康管理から、先進的な治療の選択肢まで。<br/>患者さまの今とこれからを、医師が一緒に考えます。</p></section>
  <section className="treatmentGrid">{treatments.map(t=><article className={`treatment ${t.tone}`} key={t.no}><div className="cardTop"><span className="number">{t.no}</span><span className="iconWrap"><Icon name={t.icon}/></span></div><p className="cardEyebrow">{t.eyebrow}</p><h3>{t.title}</h3><h4>{t.subtitle}</h4><p className="cardText">{t.text}</p><ul>{t.points.map(p=><li key={p}><span>✓</span>{p}</li>)}</ul><a href={t.href}>{t.cta}<Icon name="arrow"/></a></article>)}</section>
  <section className="stemCell" id="stem-cell"><div className="stemCellIntro"><p className="sectionEyebrow">PRIVATE REGENERATIVE CARE</p><p className="stemCellBadge">完全予約制・1日少人数限定</p><h2>銀座の小さな空間で、<br/>一人ひとりに向き合う<br/><em>ブティック型再生医療。</em></h2><p>患者さまご自身の脂肪から培養した間葉系幹細胞を用いる、自己由来幹細胞治療です。大規模な施設ではなく、医師が診察から治療後のフォローまで丁寧に関わる、少人数制の診療を大切にしています。</p><div className="stemCellFeatures"><div><b>01</b><span>ご本人由来の<br/>培養幹細胞</span></div><div><b>02</b><span>1回あたり<br/>1億細胞</span></div><div><b>03</b><span>医師による<br/>個別治療計画</span></div></div></div><div className="pricePanel"><p className="priceLabel">SELF-DERIVED STEM CELL THERAPY</p><h3>自己脂肪由来幹細胞治療</h3><p className="priceNote">初めて治療を検討される方へ</p><div className="priceRow featured"><span><small>初回導入価格</small><b>1回・1億細胞</b></span><strong><small>税込</small>132<small>万円</small></strong></div><div className="priceRow"><span><small>2回目以降</small><b>1回・1億細胞</b></span><strong><small>税込</small>165<small>万円</small></strong></div><p className="priceCaution">治療の適応、投与回数・間隔は診察のうえ医師が判断します。初回導入価格には適用条件があります。詳しい費用と含まれる項目は診察時にご説明します。</p><a className="stemCta" href="mailto:info@grandeternity.jp?subject=自己由来幹細胞治療の相談">幹細胞治療について相談する <Icon name="arrow"/></a></div></section>
  <section className="medicalNotice"><h3>治療を検討される方へ</h3><div><p>本治療は自由診療で、公的医療保険は適用されません。再生医療等提供計画に定められた対象・方法に基づき、診察と検査を行ったうえで適応を判断します。</p><p>治療効果には個人差があり、効果を保証するものではありません。脂肪採取部位の痛み・出血・腫れ・感染、点滴に伴う発熱・悪寒・アレルギー反応、血栓・塞栓等が生じる可能性があります。診察時に期待できること、限界、代替治療を含めて医師が説明します。</p></div></section>
  <section className="philosophy" id="philosophy"><div className="philosophyArt" aria-hidden="true"><div className="rings clinicLogo"><img src="/clinic-logo.png" alt="" width="1460" height="2048"></div><div className="philosophyWordmark"><span className="clinicWordmark"><img src="/clinic-brand.png" alt="GRAND ETERNITY グランエタニティ銀座 クリニック" width="1460" height="2048"></span></div></div><div className="philosophyText"><p className="sectionEyebrow">OUR PHILOSOPHY</p><h2>医療を、もっと身近に。<br/>未来を、もっと明るく。</h2><p>私たちは、一方的に治療を決めるのではなく、患者さまのお悩みや価値観を丁寧に伺うことから始めます。医学的な根拠と安全性を大切にしながら、納得して選べる医療を目指しています。</p><div className="values"><div><b>01</b><span>丁寧な<br/>カウンセリング</span></div><div><b>02</b><span>一人ひとりに合う<br/>治療計画</span></div><div><b>03</b><span>安心できる<br/>フォロー体制</span></div></div></div></section>
  <section className="contact" id="contact"><div><p className="sectionEyebrow">CONTACT</p><h2>まずはお気軽に<br/>ご相談ください。</h2><p>治療の適応や費用について、医師が丁寧にご説明します。</p></div><div className="contactActions"><a href="https://ge-ginza.clinic/reservation/"><Icon name="screen"/><span><small>24時間受付</small><b>オンライン診療を予約</b></span><Icon name="arrow"/></a><a href="tel:03-3528-6320"><Icon name="phone"/><span><small>お電話でのお問い合わせ</small><b>03-3528-6320</b></span><Icon name="arrow"/></a><a href="mailto:info@grandeternity.jp"><Icon name="mail"/><span><small>メールでのお問い合わせ</small><b>info@grandeternity.jp</b></span><Icon name="arrow"/></a></div></section>
  <section className="access" id="access"><div><p className="sectionEyebrow">ACCESS</p><h2>銀座一丁目の<br/>静かなクリニック。</h2></div><div className="address"><Icon name="pin"/><div><b>グランエタニティ銀座クリニック</b><p>〒104-0061<br/>東京都中央区銀座1-20-14<br/>銀座NKビル301</p><a href="https://maps.google.com/?q=東京都中央区銀座1-20-14+銀座NKビル301">Google Mapsで見る <Icon name="arrow"/></a></div></div></section>
  <footer><div className="brand footerBrand"><span className="brandMark clinicLogo"><img src="/clinic-logo.png" alt="" width="1460" height="2048"></span><span className="clinicWordmark"><img src="/clinic-brand.png" alt="GRAND ETERNITY グランエタニティ銀座 クリニック" width="1460" height="2048"></span></div><p>診療は完全予約制です。自由診療では公的医療保険が適用されず、治療費は全額自己負担となります。治療の内容・費用・主なリスクや副作用については、診察時に医師より説明します。</p><small>© GRAND ETERNITY GINZA CLINIC</small></footer>
</main> }
